apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: bankapp
  labels:
    app: mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql
        image: mysql:8.0

        ports:
        - containerPort: 3306

        envFrom:
        - configMapRef:
            name: bankapp-config-map
        - secretRef:
            name: bankapp-secrets

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
       
          initialDelaySeconds: 15
          periodSeconds: 10

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
